### ISSUE TITLE
Response field "RideId" should be "RidesId"

### ISSUE THREAD

**Issue by wjyoung** [aws-samples/aws-serverless-workshops#112]
Error returned by Lambda console test is

```
{
  "statusCode": 500,
  "body": "{\"Error\":\"One or more parameter values were invalid: Missing the key RidesId in the item\",\"Reference\":\"049727f3-6456-11e8-b9eb-bbef4e5da3e8\"}",
  "headers": {
    "Access-Control-Allow-Origin": "*"
  }
}
```

Test is:

```
{
  "path": "/ride",
  "httpMethod": "POST",
  "headers": {
    "Accept": "*/*",
    "Authorization": "eyJraWQiOiJLTzRVMWZs",
    "content-type": "application/json; charset=UTF-8"
  },
  "queryStringParameters": null,
  "pathParameters": null,
  "requestContext": {
    "authorizer": {
      "claims": {
        "cognito:username": "the_username"
      }
    }
  },
  "body": "{\"PickupLocation\":{\"Latitude\":47.6174755835663,\"Longitude\":-122.28837066650185}}"
}
```

The test passes after changing `RideId` to RidesId on lines 59 and 92 of `index.js` (i.e. the lambda function). Not sure if it's the test or the scrip that needs to change.

**Comment by mikedeck** [comment]
That looks like an issue where you've defined the partition key for your DynamoDB Rides table to be `RidesId` instead of `RideId`. The provided code is consistent with the instructions in [Module 3, part 1, step 4](https://github.com/aws-samples/aws-serverless-workshops/tree/master/WebApplication/3_ServerlessBackend#1-create-an-amazon-dynamodb-table).
