### ISSUE TITLE
an error occured when requesting your unicorn:undefined

### ISSUE THREAD

**Issue by rmit-s3342707-HAOQUAN-DAI** [aws-samples/aws-serverless-workshops#97]
Hi
I have a problem at very last stage for the webapplication, which is the error message after i click on map then request unicorn, an message occured: an error occured when requesting your unicorn:undefined

I am new with AWS, so I actually went through the whole process twice, just to make sure every step is right,but both end with same error message, so have to come here seek help.
any idea what could be wrong ? 

many thanks

**Comment by srinu49** [comment]
I too got the same error, Please help someone.

**Comment by mikedeck** [comment]
If you still have your environment up, is it possible to take a look via the developer tools in your browser at the actual request being made to your API? Can you see whether the request is being made at all and what the response is?

**Comment by mikedeck** [comment]
Also, you should see some additional details printed to the JavaScript console in the event of an error here. If you could add those details here, that would be helpful.

**Comment by srinu49** [comment]
HTML1300: Navigation occurred.
ride.html (1,1)

 CSS3121: The media query -ms-viewport has been deprecated.

 Error requesting ride:  error , Details:  
ride.js (34,17)

 Response:  undefined
ride.js (35,17)

 HTTP401: DENIED - The requested resource requires user authentication.
(XHR)OPTIONS - https://qys9xj0tz7.execute-api.us-east-1.amazonaws.com/prod/ride

**Comment by srinu49** [comment]
error: function ajaxError(jqXHR, textStatus, errorThrown) {
               console.error('Error requesting ride: ', textStatus, ', Details: ', errorThrown);                 //line 34
                console.error('Response: ', jqXHR.responseText);                                                         //line 35   
                alert('An error occured when requesting your unicorn:\n' + jqXHR.responseText);
            }

**Comment by mikedeck** [comment]
That error is caused because the Authorization header you're sending is not valid or your API Gateway authorization settings are not configured correctly.

You should be able to get the auth token by clicking on link in the message that says "You are authenticated. Click to see your auth token." in the right side of the map view. If you copy that token you can use it to test your authorizer config in API Gateway. Open the API Gateway console, click on the WildRydes API then select "Authorizers" in the left nav. Click on the "Test" link at the bottom of the CognitoAuthorizer card. Paste your token in and see if you get a 200 response.

If you're not getting a 200, it probably means you have a different user pool configured in the authorizer compared to the webapp. Make sure the user pool ID in the API Gateway config is the same as the one you have in your config.js file.

If the authorizer test works through the API Gateway console, make sure the same token you copied is actually getting passed in the Autorization HTTP header on the POST request made to /ride.

**Comment by srinu49** [comment]
@mikedeck  Thanks you for your support, I rectified the error and everything is fine. How to see the logs for this application, in my cloud watch  logs groups it is showing   "Log group not found
The log group /aws/lambda/RequestUnicorn could not be found. Check if it was correctly created and retry."

**Comment by mikedeck** [comment]
Sounds like you may have named your function something different than RequestUnicorn or you’re looking in the wrong region.

If you open your function in the console and then click on the “Monitoring” link next to “Configuration” above the code editor, that will show you a dashboard of CloudWatch metrics. You can click the jump to logs link on one of those metric graphs to get to the correct log group as well.

I’m going to go ahead and close this issue now since it seems to have been resolved.

**Comment by bil9000** [comment]
I think you may want to re-open this.I have also gone through this very carefully and followed the instructions and am getting the same error.

> An error occured when requesting your unicorn:
> undefined

I think there may be a typo in the code somewhere. For example, the word "occured" in the error above is also spelled wrong.

**Comment by geblix3000** [comment]
Same here. Any Solutions?

**Comment by bil9000** [comment]
I deleted the APIGateway code and re-did it, carefully copying  and pasting everything into the fields (typos and all) That seemed to work.

**Comment by qualnite** [comment]
I changed browser to Chrome. it worked :)

**Comment by alvinwleung** [comment]
Specifically to the undefined error, be sure to create the POST command underneath '/ride' and not under the top level '/'

**Comment by SanjayS5** [comment]
I'm not seeing any post requests go through. I have a 403 on an option request for some reason. In my API, I created the "ride" resource and it automatically created an option method. I have since deleted that and redeployed, still seeing the option method going through.

**Comment by pebblehut** [comment]
My issue was "Authorization not configured". I had failed to set the Authorization for my POST Method Request. It was None, should have been [Cognito user pool authorizers/WildRydes]. Thanks to [this Stackoverflow post](https://stackoverflow.com/questions/46185613/aws-api-gateway-method-test-error-authorization-not-configured).

**Comment by YunJae028** [comment]
Resources -> Actions -> Enable CORS

**Comment by RubyJane88** [comment]
My undefined issue was because I forgot the select or click the < Enable API Gateway CORS for the resource>.

**Comment by AyaMoustafaFahmy** [comment]
I solved my issue by signing out and re sign in again,

**Comment by AyaMoustafaFahmy** [comment]
I had the same issue , and solved it by signing out and re sign in again .

**Comment by Darren996** [comment]
On the API Gateway | /rides | POST | Method Request Card | Authorization you have to edit and select WildRydes from the drop down AND click that check button to get your changes to stick...
